sudo: required
services:
    - docker
env:
    global:
        - GIT_SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - echo "$DOCKER_PASSWORD" | docker login -u "$Docker_USERNAME" --password-stdin
    - docker build -t titoeb/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true USERNAME/react-test npm test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master